### ISSUE TITLE
Performance issue: Unnecessary check on every single call

### ISSUE THREAD

**Issue by deepakshrma** [lawrencec/Unroll#5]
unroll method check for unroll.grammar value if it is not defined it calls unroll.use method. We can avoid this call by restrict user not to use undefined grammar type.

I have created a pull request. Kindly verify the same. 
https://github.com/lawrencec/Unroll/pull/4

**Comment by lawrencec** [comment]
Thanks. 

Latest codebase makes the grammar function and throws an error if not specified by user.
